data:
  train_path: data/processed/train
  test_path: data/processed/test # Added for test dataset
model:
  num_classes: 14
  lr: 0.001
training:
  epochs: 50
  batch_size: 32
  val_ratio: 0.1 # Added for validation split
  patience: 5 # Added for early stopping
